---
apiVersion: admissionregistration.k8s.io/v1
kind: MutatingWebhookConfiguration
metadata:
  name: mutating-webhook-configuration
webhooks:
- admissionReviewVersions:
  - v1
  clientConfig:
    service:
      name: webhook-service
      namespace: system
      path: /mutate-gpu-ppchk-dev-v1-gpuworkload
  failurePolicy: Fail
  name: mgpuworkload-v1.kb.io
  rules:
  - apiGroups:
    - gpu.ppchk.dev
    apiVersions:
    - v1
    operations:
    - CREATE
    - UPDATE
    resources:
    - gpuworkloads
  sideEffects: None
- admissionReviewVersions:
  - v1
  clientConfig:
    service:
      name: webhook-service
      namespace: system
      path: /mutate-v1-pod
  failurePolicy: Fail
  name: mpstrigger.ppchk.dev
  rules:
  - apiGroups:
    - ""
    apiVersions:
    - v1
    operations:
    - CREATE
    resources:
    - pods
  sideEffects: None
---
apiVersion: admissionregistration.k8s.io/v1
kind: ValidatingWebhookConfiguration
metadata:
  name: validating-webhook-configuration
webhooks:
- admissionReviewVersions:
  - v1
  clientConfig:
    service:
      name: webhook-service
      namespace: system
      path: /validate-gpu-ppchk-dev-v1-gpuworkload
  failurePolicy: Fail
  name: vgpuworkload-v1.kb.io
  rules:
  - apiGroups:
    - gpu.ppchk.dev
    apiVersions:
    - v1
    operations:
    - CREATE
    - UPDATE
    resources:
    - gpuworkloads
  sideEffects: None
